name: Flutter Web
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: echo "Iniciando build web"
      - run: ls -lah
      - run: cd app
      - run: pwd
      - run: ls -lah
      - run: flutter build web
      - run: ls build/web
